name: Bazel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: bazelbuild/setup-bazelisk@v2
      - uses: ./.github/workflows/thirdparty/setup-bazelisk
      - run: sudo apt-get install -y yamllint
      - run: bazel build //...
      - run: bazel test //...
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Local Action Call
        uses: ./.github/workflows/specific-tests
